# Generated by Django 6.0 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0053_recommended_banners_and_card_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
