# Generated by Django 6.0 on 2026-09-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0054_socialaccount_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_uma',
            field=models.ForeignKey(blank=True, help_text='The uma this person picked as their picture. Takes precedence over the provider avatar. Blank means the provider picture.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calculatorapi.uma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='A name the person chose for themselves, shown to them alone. Blank means they use the handle. Not unique.', max_length=32),
        ),
    ]
