# Generated by Django 6.0 on 2026-09-13 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0055_customuser_display_name_avatar_uma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_uma',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='avatar_url',
        ),
        migrations.CreateModel(
            name='UserOshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oshi_of', to='calculatorapi.uma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oshis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Oshi',
                'verbose_name_plural': 'User Oshis',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('user', 'position'), name='unique_oshi_position'), models.UniqueConstraint(fields=('user', 'uma'), name='unique_oshi_uma')],
            },
        ),
    ]
