# Generated by Django 6.0 on 2026-09-13 05:50

import django.db.models.functions.text
from django.db import migrations, models


def blank_duplicate_display_names(apps, schema_editor):
    """Keep the earliest account's name, blank the later duplicates.

    display_name shipped in 0055 without a uniqueness rule, so a database that
    ran it may hold two accounts on the same name (ignoring case) and the
    constraint below would refuse to build. Prod never ran 0055 before this
    migration; this is insurance for local databases.
    """
    CustomUser = apps.get_model("calculatorapi", "CustomUser")
    seen = set()
    for user in CustomUser.objects.exclude(display_name="").order_by("pk"):
        key = user.display_name.lower()
        if key in seen:
            user.display_name = ""
            user.save(update_fields=["display_name"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calculatorapi', '0056_oshi_replaces_avatars'),
    ]

    operations = [
        migrations.RunPython(blank_duplicate_display_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='A name the person chose for themselves. Blank means they use the handle. Unique among non-blank names, ignoring case.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), condition=models.Q(('display_name', ''), _negated=True), name='unique_display_name_ci'),
        ),
    ]
