"""
The admin-editable site content: two prose pages and the FAQ.

Creates the tables and then seeds them from calculatorapi/data/site_content/
(about.md, carat-income-guide.md, faq.yaml), which are the words the frontend
used to ship in its own bundle. get_or_create by slug, so a rerun creates
nothing and never overwrites an edit made in the admin. From here on the
database owns the text; the files are only what a fresh database starts from.

The reverse drops the tables (the auto-generated CreateModel reversals), so the
seed step reverses to a no-op.
"""

# Generated by Django 6.0 on 2026-09-15 19:17

import django.db.models.deletion
from django.db import migrations, models

from calculatorapi import site_content_seed


def seed_site_content(apps, schema_editor):
    site_content_seed.seed(
        apps.get_model("calculatorapi", "SitePage"),
        apps.get_model("calculatorapi", "FaqCategory"),
        apps.get_model("calculatorapi", "FaqItem"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0057_unique_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Lowercase, hyphens, no spaces: the section's anchor on the FAQ page (/faq#the-numbers). Don't change it once published.", max_length=80, unique=True)),
                ('title', models.CharField(help_text='The section heading.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sections appear lowest number first.')),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'About'), ('carat-income-guide', 'Carat income guide')], help_text="Which page this is. Fixed: each one has a route in the site's code.", unique=True)),
                ('title', models.CharField(help_text='The page heading. Also the browser tab title.', max_length=120)),
                ('meta_description', models.CharField(help_text="One or two sentences search engines show under the page's title. Not shown on the page itself.", max_length=300)),
                ('body', models.TextField(help_text='The page text, in markdown. Blank line between paragraphs, ## for a section heading, **bold**, [link text](/faq).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Lowercase, hyphens, no spaces: the question's anchor (/faq#do-i-need-an-account). Links elsewhere point at it, so don't change it once published, even if you reword the question.", max_length=80, unique=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Markdown. Blank line between paragraphs, **bold**, [link text](/privacy-policy).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Questions in a section appear lowest number first.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Show this question in the short FAQ teaser on the homepage.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculatorapi.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ question',
                'verbose_name_plural': 'FAQ questions',
                'ordering': ('category__order', 'order', 'id'),
            },
        ),
        migrations.RunPython(seed_site_content, migrations.RunPython.noop),
    ]
