# Generated by Django 6.0 on 2026-09-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0059_uma_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('speed', 'Speed'), ('stamina', 'Stamina'), ('power', 'Power'), ('guts', 'Guts'), ('wit', 'Wit'), ('friend', 'Friend'), ('group', 'Group')], default='', help_text='What the card trains. Blank until imported.', max_length=10),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='character_id',
            field=models.PositiveIntegerField(blank=True, help_text="The game's character id (e.g. 1006 for Oguri Cap). Not an uma row.", null=True),
        ),
        migrations.AddField(
            model_name='supportcard',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The card\'s title from the game, e.g. "[Get Lots of Hugs for Me]".', max_length=100),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_dirt',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Dirt aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_end',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='End closer aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_front',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Front runner aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_late',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Late surger aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_long',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Long distance aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_medium',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Medium distance aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_mile',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Mile aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_pace',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Pace chaser aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_short',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Short distance aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='apt_turf',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'G'), (2, 'F'), (3, 'E'), (4, 'D'), (5, 'C'), (6, 'B'), (7, 'A'), (8, 'S')], help_text='Turf aptitude.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='base_guts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Guts at the initial star count.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='base_power',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Power at the initial star count.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='base_speed',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Speed at the initial star count.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='base_stamina',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Stamina at the initial star count.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='base_wit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Wit at the initial star count.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='growth_guts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Guts growth bonus, percent.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='growth_power',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Power growth bonus, percent.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='growth_speed',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Speed growth bonus, percent.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='growth_stamina',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Stamina growth bonus, percent.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='growth_wit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Wit growth bonus, percent.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='rarity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★1'), (2, '★2'), (3, '★3')], help_text='Initial star count. Sets "Is ★3" on import; that box is what the selector pickers read.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='running_style',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Front runner'), (2, 'Pace chaser'), (3, 'Late surger'), (4, 'End closer')], help_text='Default strategy.', null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The outfit\'s title from the game, e.g. "[Special Dreamer]".', max_length=100),
        ),
    ]
