# Generated by Django 6.0 on 2026-09-16 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0060_uma_support_game_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(help_text="The game's skill id. Evolved ids reach nine digits.", unique=True)),
                ('name', models.CharField(help_text='The global English name.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="The game's own description text. Shown by default.")),
                ('description_detailed', models.TextField(blank=True, default='', help_text='A fan translation with the concrete numbers, for a future "detailed" toggle. Blank until that source is imported.')),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'White'), (2, 'Gold'), (3, 'Unique (★1/★2)'), (4, 'Unique (upgraded at ★3)'), (5, 'Unique'), (6, 'Evolved')])),
                ('group_id', models.PositiveIntegerField(help_text='Shared by the white, gold and × versions of one effect.')),
                ('tier', models.SmallIntegerField(choices=[(-1, '× penalty'), (1, '○ white'), (2, '◎ gold')], help_text='Which version within the group this is.')),
                ('icon_id', models.PositiveIntegerField(help_text='One of 63 generic icons, shared by every skill of its kind.')),
                ('cost', models.PositiveSmallIntegerField(blank=True, help_text='Skill points to learn it. Uniques have no cost.', null=True)),
                ('precondition', models.TextField(blank=True, default='', help_text="The game's raw precondition string, kept verbatim for a later parser.")),
                ('condition', models.TextField(blank=True, default='', help_text="The game's raw activation condition string, kept verbatim.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills/')),
                ('admin_comments', models.TextField(blank=True, help_text='Notes for editors.', null=True)),
                ('evolves_from', models.ForeignKey(blank=True, help_text='For an evolved skill, the skill it evolved from. Empty on global for now.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='calculatorapi.skill')),
            ],
            options={
                'ordering': ('name', 'game_id'),
            },
        ),
    ]
