# Generated by Django 6.0 on 2026-09-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0061_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmaSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('unique', 'Unique'), ('innate', 'Innate'), ('awakening', 'Awakening'), ('evolved', 'Evolved')], max_length=10)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='Awakening rank (2 to 5), or the star count a unique applies from.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes for editors.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umas', to='calculatorapi.skill')),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='calculatorapi.uma')),
            ],
            options={
                'verbose_name': 'uma skill',
                'verbose_name_plural': 'uma skills',
                'ordering': ('source', 'level', 'skill__name'),
                'constraints': [models.UniqueConstraint(fields=('uma', 'skill', 'source'), name='unique_uma_skill_source')],
            },
        ),
    ]
