# Generated by Django 6.0 on 2026-09-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0062_uma_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hint', 'Hint'), ('event', 'Event')], max_length=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes for editors.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_cards', to='calculatorapi.skill')),
                ('support_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='calculatorapi.supportcard')),
            ],
            options={
                'verbose_name': 'support card skill',
                'verbose_name_plural': 'support card skills',
                'ordering': ('source', 'skill__name'),
                'constraints': [models.UniqueConstraint(fields=('support_card', 'skill', 'source'), name='unique_support_card_skill_source')],
            },
        ),
    ]
