# Generated by Django 6.0 on 2026-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0063_support_card_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='uma',
            name='image_borderless',
            field=models.ImageField(blank=True, help_text='The same art without the rarity border. Optional.', null=True, upload_to='umas_borderless/', verbose_name='borderless image'),
        ),
    ]
