# Generated by Django 6.0 on 2026-09-17 03:49

from django.db import migrations, models

# ★2 stands in for "not ★3" on a row an editor had unticked by hand. The box only
# ever said "not ★3", never which of ★1/★2, and these umas are not on global so
# the game files cannot say either. Nothing reads 1 versus 2 yet; an editor can
# correct one in the admin, and the import overwrites it once the uma releases.
NOT_THREE_STAR = 2


def carry_data_forward(apps, schema_editor):
    """Fill SupportCard.rarity, and keep every hand-unticked "Is ★3" box.

    Runs BETWEEN adding the new column and dropping the old one, which is the
    only moment both exist.
    """
    SupportCard = apps.get_model("calculatorapi", "SupportCard")
    Uma = apps.get_model("calculatorapi", "Uma")

    # A support card id starts with its rarity: 1 R, 2 SR, 3 SSR. Historical
    # models have no custom save() or helpers, so the rule is restated here.
    # import_game_data writes the game's own value over this for global cards.
    for card in SupportCard.objects.filter(game_id__isnull=False, rarity__isnull=True):
        first_digit = int(str(card.game_id)[0])
        if first_digit in (1, 2, 3):
            card.rarity = first_digit
            card.save(update_fields=["rarity"])

    # An unknown rarity counts as ★3 from here on, so an unticked row with no
    # rarity would quietly come back into the selector pickers without this.
    Uma.objects.filter(is_three_star=False, rarity__isnull=True).update(
        rarity=NOT_THREE_STAR
    )


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0064_uma_image_borderless'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcard',
            name='rarity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'R'), (2, 'SR'), (3, 'SSR')], help_text='R, SR or SSR. Blank only for a card with no game id.', null=True),
        ),
        migrations.AlterField(
            model_name='uma',
            name='rarity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★1'), (2, '★2'), (3, '★3')], help_text='Initial star count. Selectors and step-ups only grant ★3 umas, so ★1 and ★2 are hidden from the pickers. Blank counts as ★3. Imported for umas on global; set it by hand for one that is not there yet.', null=True),
        ),
        # Irreversible in spirit: the box is gone, so going backwards re-adds the
        # column at its default and leaves the rarities in place.
        migrations.RunPython(carry_data_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='uma',
            name='is_three_star',
        ),
    ]
