# Generated by Django 6.0 on 2026-09-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0067_backfill_main_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_shards', models.IntegerField(default=0)),
                ('sr_crystals', models.IntegerField(default=0)),
                ('ssr_shards', models.IntegerField(default=0)),
                ('ssr_crystals', models.IntegerField(default=0)),
                ('daily_carat', models.BooleanField(default=False)),
                ('training_pass', models.BooleanField(default=False)),
                ('misc_earnings', models.BooleanField(default=True)),
                ('monthly_shop_tickets', models.BooleanField(default=True)),
                ('discounted_paid_pulls', models.BooleanField(default=True)),
                ('full_price_paid_pulls', models.BooleanField(default=True)),
                ('include_purchases_in_projection', models.BooleanField(default=False)),
                ('webstore_bonus', models.BooleanField(default=False)),
                ('current_carat', models.IntegerField(default=0)),
                ('current_paid_carat', models.IntegerField(default=0)),
                ('uma_ticket', models.IntegerField(default=0)),
                ('support_ticket', models.IntegerField(default=0)),
                ('uma_selector_ticket', models.IntegerField(default=0)),
                ('support_selector_ticket', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champions_meeting_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.championsmeetingrank')),
                ('club_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.clubrank')),
                ('league_of_heroes_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.leagueofheroesrank')),
                ('team_trials_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculatorapi.teamtrialsrank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='income_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='calculatorapi.incomeprofile'),
        ),
    ]
