# Generated by Django 6.0 on 2026-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0068_income_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplannedbanner',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
