# Generated by Django 6.0 on 2026-09-22 20:21
#
# Drops the feedback inbox, rows included. The site's feedback form was replaced
# by a link to the Discord server on 2026-09-22 (web #90), and the decision was
# to delete every message the form had collected rather than keep a read-only
# archive: the rewritten privacy policy describes no such store, and a table
# nothing writes to or reads from is only a liability. Irreversible for the rows.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0069_planned_banner_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
