# Generated by Django 6.0 on 2026-09-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0070_drop_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplannedpurchase',
            name='income_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_purchases', to='calculatorapi.incomeprofile'),
        ),
    ]
