# Generated by Django 6.0 on 2026-10-01 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0071_planned_purchase_income_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationconstants',
            name='monthly_shop_support_tickets_max',
            field=models.IntegerField(default=9, help_text="Most support tickets the shop sells in a month. Caps a player's own count.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='monthly_shop_uma_tickets_max',
            field=models.IntegerField(default=9, help_text="Most uma tickets the shop sells in a month. Caps a player's own count.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_support_tickets_bought',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_uma_tickets_bought',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spend_tickets_on_banners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='shop_support_tickets_bought',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='shop_uma_tickets_bought',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='spend_tickets_on_banners',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calculationconstants',
            name='monthly_shop_support_tickets',
            field=models.IntegerField(default=4, help_text='Support tickets a player is assumed to buy from the shop each month, until they set their own count.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='calculationconstants',
            name='monthly_shop_uma_tickets',
            field=models.IntegerField(default=4, help_text='Uma tickets a player is ASSUMED to buy from the shop each month, until they set their own count. Matches the source sheet.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
