# Generated by Django 6.0 on 2026-10-05 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0072_ticket_spend_toggle_and_shop_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationconstants',
            name='daily_legend_race_event_pieces',
            field=models.IntegerField(default=80, help_text="Pieces a player got from that uma's original limited Legend Race event (about 3 days, 3 races a day), if they played it.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='daily_legend_race_piece_goal',
            field=models.IntegerField(default=150, help_text="Pieces a player grinds one uma toward. The page counts the days to reach this, from zero and from the event's pieces below.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='daily_legend_race_pieces_per_day',
            field=models.IntegerField(default=1, help_text='Pieces one daily legend race gives. One race a day per uma.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(choices=[('about', 'About'), ('carat-income-guide', 'Carat income guide'), ('daily-legend-races', 'Daily legend races')], help_text="Which page this is. Fixed: each one has a route in the site's code.", unique=True),
        ),
        migrations.CreateModel(
            name='DailyLegendRaceRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What the batch is called on the site, e.g. "2nd Anniversary".', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='daily_legend_races/')),
                ('offset_days', models.SmallIntegerField(default=0, help_text="Days to add to the banner's start date. Use a minus sign to subtract. 0 means the same day as the banner.")),
                ('banner_timeline', models.ForeignKey(blank=True, help_text="The banner this batch arrives with, usually the anniversary's last part. Its start date is the batch's date. Leave it blank to keep the batch off the site until the timeline reaches it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_legend_race_releases', to='calculatorapi.bannertimeline')),
            ],
            options={
                'verbose_name': 'daily legend race release',
                'verbose_name_plural': 'daily legend race releases',
            },
        ),
        migrations.CreateModel(
            name='DailyLegendRaceUma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uma_links', to='calculatorapi.dailylegendracerelease')),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculatorapi.uma')),
            ],
            options={
                'verbose_name': 'uma',
                'verbose_name_plural': 'umas',
            },
        ),
        migrations.AddField(
            model_name='dailylegendracerelease',
            name='umas',
            field=models.ManyToManyField(related_name='daily_legend_race_releases', through='calculatorapi.DailyLegendRaceUma', to='calculatorapi.uma'),
        ),
        migrations.AddConstraint(
            model_name='dailylegendraceuma',
            constraint=models.UniqueConstraint(fields=('uma',), name='one_daily_legend_race_per_uma', violation_error_message='This uma is already in another daily legend race release.'),
        ),
    ]
