# Generated by Django 6.0 on 2026-10-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0074_seed_daily_legend_races_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationconstants',
            name='daily_legend_race_event_pieces',
        ),
        migrations.RemoveField(
            model_name='calculationconstants',
            name='daily_legend_race_piece_goal',
        ),
        migrations.RemoveField(
            model_name='calculationconstants',
            name='daily_legend_race_pieces_per_day',
        ),
    ]
