# Generated by Django 6.0 on 2026-10-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Help text only: no table changes.

    A batch with no banner used to be hidden on the site. It now shows on the
    Legend Races tab as tentative, and the field's help text says so. Django
    records help text in its migration state, so the wording change needs
    this file even though it runs no SQL.
    """

    dependencies = [
        ('calculatorapi', '0075_drop_legend_race_grind_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylegendracerelease',
            name='banner_timeline',
            field=models.ForeignKey(blank=True, help_text="The banner this batch arrives with, usually the anniversary's last part. Its start date is the batch's date. Leave it blank while the timeline has no banner for it yet: the batch then shows on the Legend Races tab as tentative, with no date.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_legend_race_releases', to='calculatorapi.bannertimeline'),
        ),
    ]
