# Generated by Django 6.0 on 2026-10-06 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0076_legend_race_banner_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersupport',
            name='rate_up_picks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Select banners only ("10 Select 2"): how many of the listed cards the player picks to rate up. Leave blank when every listed card is a rate-up.', null=True, verbose_name='rate-up picks'),
        ),
        migrations.AddField(
            model_name='banneruma',
            name='rate_up_picks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Select banners only ("10 Select 2"): how many of the listed cards the player picks to rate up. Leave blank when every listed card is a rate-up.', null=True, verbose_name='rate-up picks'),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_pool_1',
            field=models.DecimalField(decimal_places=6, default='0.050000', help_text='The most the ★1 / R rate-ups can share between them (0.05 = 5%).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_pool_2',
            field=models.DecimalField(decimal_places=6, default='0.030000', help_text='The most the ★2 / SR rate-ups can share between them (0.03 = 3%).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_pool_3',
            field=models.DecimalField(decimal_places=6, default='0.030000', help_text='The most the ★3 / SSR rate-ups can share between them (0.03 = 3%). Only matters when there are more than four of them.', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_rate_1',
            field=models.DecimalField(decimal_places=6, default='0.037500', help_text='Per-pull chance of one ★1 / R rate-up card (0.0375 = 3.75%).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_rate_2',
            field=models.DecimalField(decimal_places=6, default='0.022500', help_text='Per-pull chance of one ★2 / SR rate-up card (0.0225 = 2.25%).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='calculationconstants',
            name='rate_up_rate_3',
            field=models.DecimalField(decimal_places=6, default='0.007500', help_text='Per-pull chance of one ★3 / SSR rate-up card, as a decimal (0.0075 = 0.75%).', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='supportsonsupportbanner',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Only when this card's rate breaks the usual rule, as a decimal: 0.005 for 0.5%. Leave blank and the calculator works it out from rarity and how many cards share the rate-up. Copy the number from the in-game rates page.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='rate override'),
        ),
        migrations.AddField(
            model_name='umasonumabanner',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Only when this card's rate breaks the usual rule, as a decimal: 0.005 for 0.5%. Leave blank and the calculator works it out from rarity and how many cards share the rate-up. Copy the number from the in-game rates page.", max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='rate override'),
        ),
    ]
