# Generated by Django 6.0 on 2026-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0077_rate_up_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplannedbanner',
            name='primary_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplannedbanner',
            name='second_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
