# Generated by Django 6.0 on 2026-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0079_backfill_rate_up_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplannedbanner',
            name='primary_target',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
