# Generated by Django 6.0 on 2026-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapi', '0081_analytics_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('route', models.CharField(max_length=40)),
                ('page_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Landing Page Visit',
                'verbose_name_plural': 'Landing Page Visits',
                'ordering': ['-date', 'route'],
                'constraints': [models.UniqueConstraint(fields=('date', 'route'), name='one_landing_row_per_day_and_route')],
            },
        ),
        migrations.CreateModel(
            name='ReferrerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('host', models.CharField(max_length=100)),
                ('page_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Referrer Visit',
                'verbose_name_plural': 'Referrer Visits',
                'ordering': ['-date', 'host'],
                'constraints': [models.UniqueConstraint(fields=('date', 'host'), name='one_referrer_row_per_day_and_host')],
            },
        ),
    ]
